### PR TITLE
Dont disable petsc just because mpi is disabled

### LINKED ISSUE #1: Don't disable petsc just because mpi is disabled
PETSc runs just fine without MPI. Some people just love beautiful serial code like @fdkong

### PR DESCRIPTION
**Pull request by lindsayad**
closes #1

@roystgnr. Feel free to tag your disable petsc nemesis :smile:

### CODE REVIEW

**Comment by lindsayad** [comment]
@milljm can you apply this patch and see if this results in libmesh still using petsc?

**Comment by roystgnr** [comment]
> Feel free to tag your disable petsc nemesis

I know, I was looking forward to poking fun at @benkirk for disabling this capability in [a stealth commit](https://github.com/libMesh/libmesh/commit/87effa9b4b72a44259444579da4e510cdf9d4c5f), but I looked back further and it turns out that when I enabled it that was [also via stealth commit](https://github.com/libMesh/libmesh/commit/94941d497262b6feab88c96b328a9f2da4a4b226), so there goes my moral high ground.

At least *someone's* using an actual PR this time, thank you.

Eventually we ought to actually try verifying whether our PETSc was built with MPI or in serial, so we can have --disable-mpi affect the former case but not the latter.

**Comment by milljm** [comment]
That did not seem to do the trick...

```pre
  metaphysicl...................... : yes
  metis............................ : yes
  mpi.............................. : no
  nanoflann........................ : yes
  nemesis.......................... : no
  netcdf........................... : yes
     version....................... : 4
  nlopt............................ : no
  parmetis......................... : no
  petsc............................ : no
  qhull............................ : yes
  sfcurves......................... : no
```

**Review by lindsayad — COMMENTED** [review]
Don't we still want to enable serial PETSc?

**Comment by roystgnr** [comment]
I still want serial PETSc re-enabled, sure, but "That did not seem to do the trick..." suggested that this PR wasn't doing it, no?

**Comment by lindsayad** [comment]
I don't know if this is relevant any more

**Pull request closed without merging**
